"""Add started_at and notes columns to tasks

Revision ID: cf6253b3aef1
Revises: e6d9adb81995
Create Date: 2026-04-30 15:52:46.527897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6253b3aef1'
down_revision = 'e6d9adb81995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_history_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_sla_due_date'), ['sla_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_task_id'), ['task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tasks_title'), ['title'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_column('is_admin')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_title'))
        batch_op.drop_index(batch_op.f('ix_tasks_task_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_sla_due_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_department'))
        batch_op.drop_index(batch_op.f('ix_tasks_category'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_to'))
        batch_op.drop_column('notes')
        batch_op.drop_column('started_at')

    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_history_task_id'))

    # ### end Alembic commands ###
